name: collector-sanity-check
description: Sanity checks for collector
inputs:
  working_directory:
    description: Default directory
    default: .
  oc_kcm_timeout:
    description: Default timeout
    default: 5m

runs:
  using: 'composite'
  steps:
    - name: Deploy mysql
      run: make deploy-mysql
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Deploy collector into the test Kind cluster
      run: make deploy-collector
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Wait for all pods to be ready
      run: |
        echo "Waiting for kube-controller-manager... (timeout: ${{ inputs.oc_kcm_timeout }})" && \
        oc wait -n kube-system --for=condition=ready pod --all=true --timeout=${{ inputs.oc_kcm_timeout }}
      shell: bash

    - name: Dispaly collector content
      run: ls -R
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Run sanity check on the collector
      run: ./script/sanity-check.sh
      working-directory: ${{ inputs.working_directory }}
      shell: bash
