name: collector-sanity-check
description: Sanity checks for collector

runs:
  using: 'composite'
  steps:
    - name: Deploy collector into the test Kind cluster
      run: make build-and-deploy-image-collector-dev
      shell: bash

    - name: Wait for all pods to be ready
      run: |
        echo "Waiting for kube-controller-manager... (timeout: ${{ inputs.oc_kcm_timeout }})" && \
        oc wait -n kube-system --for=condition=ready pod --all=true --timeout=${{ inputs.oc_kcm_timeout }}
      shell: bash

    - name: Run sanity check on the collector
      run: ./script/sanity-check.sh
      shell: bash
      