name: prepare-collector-for-use
description: Deploy necessary deployments for running sanity checks on collector
inputs:
  working_directory:
    description: Default directory
    default: .
  oc_collector_timeout:
    description: Default timeout
    default: 10m

runs:
  using: 'composite'
  steps:
    - name: Enable deploying mysql
      run: |
        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Deploy mysql into the test kind cluster
      run: make deploy-mysql
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Deploy collector into the test Kind cluster
      run: make deploy-collector
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Wait for all pods to be ready
      run: |
        echo "Waiting for collector... (timeout: ${{ inputs.oc_collector_timeout }})" && \
        oc wait --for=condition=ready pod --all=true -n tnf-collector --timeout=${{ inputs.oc_collector_timeout }}
      shell: bash

    - name: Port forward collector (temporarly)
      run: oc port-forward $(oc get pods -n tnf-collector -o name | grep collector) 8080:8080 -n tnf-collector &
      working-directory: ${{ inputs.working_directory }}
      shell: bash
