---
apiVersion: 1

datasources:
  - name: collector-datasource
    type: mysql
    access: proxy
    orgId: 1
    uid: 0
    url: database-collectordb-1hykanj2mxdh.cn9luyhgvfkp.us-east-1.rds.amazonaws.com:3306
    user: MysqlUsername # value in tnf-secrets/collector-secrets.json
    database: cnf
    isDefault: true
    editable: true
    secureJsonData:
      password: MysqlPassword # value in tnf-secrets/collector-secrets.json
