{
 "title": "Collector's Dashboard",
 "time": { "from": "2023-11-01T12:50:27.897Z", "to": "2023-11-01T13:00:27.897Z" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cnf",
     "rawSql": "SELECT Min(upload_time) AS earliest_time,  Max(upload_time) AS latest_time, COUNT(*) AS claim_num FROM cnf.claim;\n\n"
    }
   ]
  },
  {
   "title": "Suite Tests Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Claims",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "targets": [
      { "dataset": "cnf", "rawSql": "SELECT * FROM cnf.claim;" }
     ]
    },
    {
     "title": "Claims Results",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "dataset": "cnf",
       "rawSql": "SELECT * FROM cnf.claim_result;"
      }
     ]
    }
   ]
  },
  {
   "title": "Suite Tests Status Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Status by Suite Name",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "cnf",
       "rawSql": "SELECT\n  suite_name,\n  SUM(CASE WHEN test_status = \"passed\" THEN 1 ELSE 0 END) AS total_passed,\n  SUM(CASE WHEN test_status = \"failed\" THEN 1 ELSE 0 END) AS total_failed,\n  SUM(CASE WHEN test_status = \"skipped\" THEN 1 ELSE 0 END) AS total_skipped\nFROM cnf.claim_result\nGROUP BY suite_name;"
      }
     ]
    },
    {
     "title": "Total Status by Test ID",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dataset": "cnf",
       "rawSql": "SELECT\n  suite_name,\n  test_id,\n  SUM(CASE WHEN test_status = \"passed\" THEN 1 ELSE 0 END) AS total_passed,\n  SUM(CASE WHEN test_status = \"failed\" THEN 1 ELSE 0 END) AS total_failed,\n  SUM(CASE WHEN test_status = \"skipped\" THEN 1 ELSE 0 END) AS total_skipped\nFROM cnf.claim_result\nGROUP BY test_id;"
      }
     ]
    },
    {
     "title": "Total Status by CNF Version",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 4, "x": 7, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "cnf",
       "rawSql": "SELECT \ncnf_version,\nid AS claim_id\nFROM cnf.claim;\n  \n\n"
      },
      {
       "dataset": "cnf",
       "rawSql": "SELECT \n  claim_id,\n  SUM(CASE WHEN test_status = \"passed\" THEN 1 ELSE 0 END) AS passed_tests,\n  SUM(CASE WHEN test_status = \"failed\" THEN 1 ELSE 0 END) AS failed_tests,\n  SUM(CASE WHEN test_status = \"skipped\" THEN 1 ELSE 0 END) AS skipped_tests\nFROM\n  claim_result\nGROUP BY\n  claim_id;\n"
      }
     ]
    },
    {
     "title": "Total Status by Partner Name",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 11, "y": 21 },
     "targets": [
      {
       "dataset": "cnf",
       "rawSql": "SELECT \npartner_name,\nid AS claim_id\nFROM cnf.claim;"
      },
      {
       "dataset": "cnf",
       "rawSql": "SELECT \n  claim_id,\n  SUM(CASE WHEN test_status = \"passed\" THEN 1 ELSE 0 END) AS passed_tests,\n  SUM(CASE WHEN test_status = \"failed\" THEN 1 ELSE 0 END) AS failed_tests,\n  SUM(CASE WHEN test_status = \"skipped\" THEN 1 ELSE 0 END) AS skipped_tests\nFROM\n  claim_result\nGROUP BY\n  claim_id;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Suite Tests Usage Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Usage",
     "type": "piechart",
     "description": "Who executed the CNF certification tests.",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "cnf",
       "rawSql": "SELECT executed_by, COUNT(*) AS num \nFROM cnf.claim\nGROUP BY executed_by;"
      }
     ]
    },
    {
     "title": "Partners Usage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "cnf",
       "rawSql": "SELECT partner_name, COUNT(*) AS num \nFROM cnf.claim\nGROUP BY partner_name;"
      }
     ]
    }
   ]
  }
 ]
}