---
apiVersion: v1
kind: Secret
metadata:
  name: collector-db-creds
  namespace: default
type: Opaque
data:
  mysql-username: ${{ secrets.MYSQL_USERNAME }}
  mysql-password: ${{ secrets.MYSQL_PASSWORD }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector-container
          image: quay.io/testnetworkfunction/collector:latest
          env:
            - name: DB_URL
              value: "mysql.default.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: collector-db-creds
                  key: mysql-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: collector-db-creds
                  key: mysql-password
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: Always
