---
name: 'Publish the `collector` image'
"on":
    # Run the workflow when a new release gets published
    release:
        types: [published]
    # Run the workflow every day at 5 am UTC (1 am EST, 7am CET)
    # This is useful for keeping the image up-to-date with security
    # patches provided in the UBI.
    # Disclaimer: There is no guarantee that scheduled workflows will
    # run at the predefined time, if at all. The delay is usually
    # around 10-30 minutes.
    schedule:
        - cron: '0 5 * * *'
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    REGISTRY: quay.io
    COLLECTOR_IMAGE_NAME_AND_TAG: testnetworkfunction/collector:latest

jobs:
    push-collector-image:
        name: 'Push the `collector` image'
        runs-on: ubuntu-22.04
        steps:
            - name: Build the `cnf-certification-test` image
              run: |
                make build-collector-image
    
          # Push the new collector image to Quay.io.
            - name: Authenticate against Quay.io
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                # Use a Robot Account to authenticate against Quay.io
                # https://docs.quay.io/glossary/robot-accounts.html
                username: ${{ secrets.QUAY_ROBOT_USERNAME }}
                password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    
            - name: Push the newly built image to Quay.io
              run: docker push ${REGISTRY}/${COLLECTOR_IMAGE_NAME_AND_TAG}